"use client";

import { ChangeEvent, FormEvent, useMemo, useState } from "react";

type Step = "upload" | "configure" | "review" | "done";
type Config = { mode: "bw" | "color"; sides: "single" | "double"; copies: number; binding: "none" | "spiral" | "tape"; category: "school" | "college" | "office" | "art" };
const initialConfig: Config = { mode: "bw", sides: "single", copies: 1, binding: "none", category: "college" };
const money = (value: number) => `₹${value.toFixed(0)}`;

export default function Home() {
  const [step, setStep] = useState<Step>("upload");
  const [files, setFiles] = useState<File[]>([]);
  const [config, setConfig] = useState<Config>(initialConfig);
  const [phone, setPhone] = useState("");
  const [orderId, setOrderId] = useState("");
  const [error, setError] = useState("");
  const price = useMemo(() => { const rate = config.mode === "color" ? 10 : 2; const side = config.sides === "double" ? 0.9 : 1; const binding = config.binding === "spiral" ? 30 : config.binding === "tape" ? 10 : 0; return files.length * rate * config.copies * side + binding; }, [files, config]);
  function onFiles(event: ChangeEvent<HTMLInputElement>) { setError(""); const selected = Array.from(event.target.files ?? []); const allowed = selected.filter((file) => ["application/pdf", "image/jpeg", "image/jpg"].includes(file.type)); if (selected.length !== allowed.length) return setError("Sirf PDF ya JPG/JPEG files upload karein."); if (allowed.length > 5) return setError("Ek order mein maximum 5 files allowed hain."); if (allowed.some((file) => file.size > 40 * 1024 * 1024)) return setError("Har file ka size 40 MB se kam hona chahiye."); setFiles(allowed); }
  function submitOrder(event: FormEvent) { event.preventDefault(); if (!/^\d{10}$/.test(phone)) return setError("Valid 10-digit mobile number daalein."); setError(""); setOrderId(`KG-${new Date().getFullYear()}-${Math.floor(100000 + Math.random() * 900000)}`); setStep("done"); }
  const options = { mode: [["bw", "Black & white"], ["color", "Colour"]], sides: [["single", "Single side"], ["double", "Both sides"]], binding: [["none", "No binding"], ["spiral", "Spiral · ₹30"], ["tape", "Tape · ₹10"]], category: [["college", "College"], ["school", "School"], ["office", "Office"], ["art", "Art / craft"]] } as const;
  return <main className="min-h-screen bg-[#f7f7f4] text-[#202522]"><header className="border-b border-[#dfe3dc] bg-[#fbfbf8]"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><div><p className="text-lg font-semibold tracking-tight">Kagazz</p><p className="text-xs text-[#68736b]">Print. Collect. Done.</p></div><a className="text-sm font-medium text-[#2b6b4b] hover:underline" href="#how-it-works">How it works</a></div></header><div className="mx-auto max-w-6xl px-5 py-10">
    {step !== "done" && <div className="mb-10 flex max-w-xl items-center gap-2 text-xs font-medium text-[#68736b]">{(["Upload", "Configure", "Review"] as const).map((label, i) => <div key={label} className="flex items-center gap-2"><span className={`grid h-7 w-7 place-items-center rounded-full border ${i <= ["upload", "configure", "review"].indexOf(step) ? "border-[#2b6b4b] bg-[#2b6b4b] text-white" : "border-[#b9c3ba]"}`}>{i + 1}</span><span className="hidden sm:inline">{label}</span>{i < 2 && <span className="mx-1 h-px w-8 bg-[#cfd7d0] sm:w-16" />}</div>)}</div>}
    <div className="grid gap-12 lg:grid-cols-[1fr_380px]"><section><p className="mb-3 text-sm font-medium text-[#2b6b4b]">LOCAL PRINTING, MADE SIMPLE</p><h1 className="max-w-xl text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">Send your files.<br />Pick them up ready.</h1><p className="mt-5 max-w-lg text-base leading-7 text-[#68736b]">Upload your documents, choose print preferences, and get a clear order reference. No waiting in a WhatsApp thread.</p>
      {step === "upload" && <div className="mt-10 max-w-xl"><label className="block cursor-pointer rounded-xl border border-dashed border-[#9ead9f] bg-white p-8 text-center transition hover:border-[#2b6b4b] hover:bg-[#f8fbf7]"><input className="sr-only" type="file" accept="application/pdf,image/jpeg" multiple onChange={onFiles} /><span className="text-3xl">↑</span><span className="mt-3 block font-medium">Choose PDF or JPG files</span><span className="mt-1 block text-sm text-[#68736b]">Up to 5 files · 40 MB each</span></label>{files.length > 0 && <div className="mt-4 space-y-2">{files.map((file) => <div key={file.name} className="flex items-center justify-between border-b border-[#dfe3dc] py-2 text-sm"><span className="truncate">{file.name}</span><span className="ml-3 text-[#68736b]">{(file.size / 1024 / 1024).toFixed(1)} MB</span></div>)}<button onClick={() => setStep("configure")} className="mt-6 w-full rounded-lg bg-[#2b6b4b] px-5 py-3 font-medium text-white hover:bg-[#245c40]">Continue to print options</button></div>}</div>}
      {step === "configure" && <form className="mt-10 max-w-xl space-y-6" onSubmit={(e) => { e.preventDefault(); setStep("review"); }}><div className="grid gap-5 sm:grid-cols-2">{([ ["Print type", "mode"], ["Sides", "sides"], ["Binding", "binding"], ["For", "category"] ] as const).map(([label, key]) => <label key={key} className="text-sm font-medium">{label}<select value={config[key]} onChange={(e) => setConfig({ ...config, [key]: e.target.value as never })} className="mt-2 block w-full rounded-lg border border-[#cbd4cc] bg-white px-3 py-3 font-normal outline-none focus:border-[#2b6b4b]">{options[key].map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select></label>)}</div><label className="block text-sm font-medium">Copies<input type="number" min={1} max={100} value={config.copies} onChange={(e) => setConfig({ ...config, copies: Math.min(100, Math.max(1, Number(e.target.value))) })} className="mt-2 block w-32 rounded-lg border border-[#cbd4cc] bg-white px-3 py-3 outline-none focus:border-[#2b6b4b]" /></label><button className="w-full rounded-lg bg-[#2b6b4b] px-5 py-3 font-medium text-white hover:bg-[#245c40]">Review order</button></form>}
      {step === "review" && <form onSubmit={submitOrder} className="mt-10 max-w-xl space-y-5"><div className="border-y border-[#dfe3dc] py-5"><p className="text-sm text-[#68736b]">Your print order</p><p className="mt-2 font-medium">{files.length} file(s) · {config.copies} cop{config.copies === 1 ? "y" : "ies"}</p><p className="mt-1 text-sm text-[#68736b]">{config.mode === "bw" ? "Black & white" : "Colour"} · {config.sides === "single" ? "Single side" : "Both sides"} · {config.binding === "none" ? "No binding" : config.binding}</p></div><label className="block text-sm font-medium">Mobile number<input required inputMode="numeric" maxLength={10} value={phone} onChange={(e) => setPhone(e.target.value.replace(/\D/g, ""))} placeholder="10-digit number" className="mt-2 block w-full rounded-lg border border-[#cbd4cc] bg-white px-3 py-3 outline-none focus:border-[#2b6b4b]" /></label><p className="text-xs leading-5 text-[#68736b]">Phase 0 flow: order is placed as <b>Pay at Shop</b>. Shopkeeper will confirm payment at collection.</p><button className="w-full rounded-lg bg-[#2b6b4b] px-5 py-3 font-medium text-white hover:bg-[#245c40]">Place order · {money(price)}</button></form>}
      {error && <p role="alert" className="mt-4 rounded-lg border border-[#e2b8af] bg-[#fff7f5] px-4 py-3 text-sm text-[#963d2d]">{error}</p>}</section><aside className="self-start border-l border-[#dfe3dc] pl-0 lg:pl-10"><div className="rounded-xl bg-[#e8efe8] p-6"><p className="text-sm font-medium text-[#2b6b4b]">Why Kagazz?</p><ul className="mt-5 space-y-4 text-sm leading-6"><li><b className="block">Clear instructions</b><span className="text-[#68736b]">Your print preferences reach the shop exactly as selected.</span></li><li><b className="block">Pay at shop</b><span className="text-[#68736b]">No online payment needed for this MVP.</span></li><li><b className="block">One reference number</b><span className="text-[#68736b]">Use it to ask for your order status.</span></li></ul></div></aside></div>
    {step === "done" && <div className="mx-auto max-w-xl border-t border-[#dfe3dc] pt-12"><p className="text-sm font-medium text-[#2b6b4b]">ORDER RECEIVED</p><h2 className="mt-3 text-3xl font-semibold">Your order is in the queue.</h2><p className="mt-4 text-[#68736b]">Show this reference at the shop when collecting.</p><div className="mt-8 flex items-center justify-between rounded-xl bg-white p-5"><span className="text-sm text-[#68736b]">Reference</span><strong className="font-mono text-lg">{orderId}</strong></div><button onClick={() => { setStep("upload"); setFiles([]); setConfig(initialConfig); setPhone(""); }} className="mt-8 rounded-lg bg-[#2b6b4b] px-5 py-3 font-medium text-white">New order</button></div>}
    <section id="how-it-works" className="mt-24 border-t border-[#dfe3dc] pt-8"><p className="text-sm font-medium text-[#68736b]">A simple three-step flow</p><div className="mt-5 grid gap-6 text-sm sm:grid-cols-3"><div><b>01 · Upload</b><p className="mt-2 text-[#68736b]">PDFs and JPGs, securely submitted.</p></div><div><b>02 · Configure</b><p className="mt-2 text-[#68736b]">Choose exactly how you want it printed.</p></div><div><b>03 · Collect</b><p className="mt-2 text-[#68736b]">Bring your reference and pay at the shop.</p></div></div></section></div></main>;
}
